-- 0044_invite_variants.sql
-- Roadmap #3: AI-generated invite variants per venue, surfaced in Batches to pick.
-- Generated by the PC sync (which holds the Anthropic key). Additive.
create table if not exists public.inbox_invite_variants (
  id uuid primary key default gen_random_uuid(),
  venue text,
  body text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
alter table public.inbox_invite_variants enable row level security;
drop policy if exists inbox_invite_variants_all on public.inbox_invite_variants;
create policy inbox_invite_variants_all on public.inbox_invite_variants for all using (true) with check (true);
grant all on public.inbox_invite_variants to anon, authenticated;
create index if not exists inbox_invite_variants_venue_idx on public.inbox_invite_variants (venue, active);
